/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CcdesignFooter {
    'first': string;
    'last': string;
  }
  interface CcdesignFooterAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }

  interface CcdesignHeader {
    'first': string;
    'last': string;
  }
  interface CcdesignHeaderAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CcdesignFooter': Components.CcdesignFooter;
    'CcdesignHeader': Components.CcdesignHeader;
  }

  interface StencilIntrinsicElements {
    'ccdesign-footer': Components.CcdesignFooterAttributes;
    'ccdesign-header': Components.CcdesignHeaderAttributes;
  }


  interface HTMLCcdesignFooterElement extends Components.CcdesignFooter, HTMLStencilElement {}
  var HTMLCcdesignFooterElement: {
    prototype: HTMLCcdesignFooterElement;
    new (): HTMLCcdesignFooterElement;
  };

  interface HTMLCcdesignHeaderElement extends Components.CcdesignHeader, HTMLStencilElement {}
  var HTMLCcdesignHeaderElement: {
    prototype: HTMLCcdesignHeaderElement;
    new (): HTMLCcdesignHeaderElement;
  };

  interface HTMLElementTagNameMap {
    'ccdesign-footer': HTMLCcdesignFooterElement
    'ccdesign-header': HTMLCcdesignHeaderElement
  }

  interface ElementTagNameMap {
    'ccdesign-footer': HTMLCcdesignFooterElement;
    'ccdesign-header': HTMLCcdesignHeaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
